#Example 1
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx
      image: nginx


#Example 2
apiVersion: v1
kind: Pod
metadata:
    name: postgres
    labels: 
        tier: dbtier
spec:
    containers:
        -name: postgres
         image: postgres


#Example 3         
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    tier: db-tier
spec:
  containers:
    - name: postgres
      image: postgres
      env: 
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
